import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // ✅ CSS Import

// ✅ Baaki Imports bhi sabse upar honay chahiye
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "sonner"; // Agar ye library use kar rahe hain

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TaskFlow App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}